title: Zach Quinn # your name (or website title) here
logo: "/images/ZQ_LinkedIn.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>About:</b> Combining machine learning skill sets and leveraging journalistic training to present complex topics to non-technical audiences.
  <br><br>
  <a href="https://www.linkedin.com/in/zach-l-quinn/">Contact (via LinkedIn)</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
